build-authLambda:
	# ./gradlew :application:oauth2:jar
	unzip ./application/oauth2/build/libs/oauth2-plain.jar -d $(ARTIFACTS_DIR)

build-pocLambda:
	# ./gradlew :application:poc:jar
	unzip ./application/poc/build/libs/poc-plain.jar -d $(ARTIFACTS_DIR)
 